"""SCAMPER ideation tools. Each lens is generated by the LLM (Gemini); if no API
key is configured the tools return a deterministic stub so the server still works."""

import json

from app.llm import complete

LENSES: dict[str, str] = {
    "Substitute": "Replace a component, material, energy source, or rule with an alternative.",
    "Combine": "Merge with another product, function, or process step to create synergy.",
    "Adapt": "Borrow a mechanism from another domain or nature that already solves this.",
    "Modify": "Magnify, minify, or change an attribute — scale, geometry, timing, frequency.",
    "Put to another use": "Repurpose the thing, a by-product, or a waste stream elsewhere.",
    "Eliminate": "Remove a part, step, or constraint; simplify to the essential function.",
    "Reverse": "Invert the order, roles, or the problem itself; do the opposite.",
}


def _match(lens: str) -> str | None:
    l = (lens or "").strip().lower()
    for name in LENSES:
        if name.lower() == l or name.lower().startswith(l) or l in name.lower():
            return name
    return None


def _parse_json(text: str) -> dict:
    s, e = text.find("{"), text.rfind("}")
    if s != -1 and e != -1 and e > s:
        try:
            return json.loads(text[s : e + 1])
        except ValueError:
            pass
    return {}


def list_scamper_lenses() -> str:
    """List the seven SCAMPER lenses and what each one prompts you to do."""
    return "SCAMPER lenses:\n" + "\n".join(f"• {k}: {v}" for k, v in LENSES.items())


def apply_lens(problem: str, lens: str) -> str:
    """Generate one concrete idea for a problem using a single SCAMPER lens.
    `lens` is one of: Substitute, Combine, Adapt, Modify, Put to another use,
    Eliminate, Reverse."""
    canon = _match(lens)
    if not canon:
        return f"Unknown lens '{lens}'. Valid lenses: {', '.join(LENSES)}"
    hint = LENSES[canon]
    system = "You are an expert facilitator applying the SCAMPER ideation method. Be concrete and specific."
    user = (
        f"PROBLEM: {problem}\n"
        f"LENS: {canon} — {hint}\n"
        'Return a JSON object: {"idea": <one concrete proposal>, "rationale": <why it fits the problem>}.'
    )
    out = complete(system, user)
    if not out:  # no key / LLM unavailable → deterministic stub
        return f"[{canon}] (stub) Apply the '{canon}' lens to: {problem}"
    obj = _parse_json(out)
    idea = (obj.get("idea") or out).strip()
    rationale = (obj.get("rationale") or "").strip()
    return f"[{canon}] {idea}" + (f"\n  Rationale: {rationale}" if rationale else "")


def scamper_ideate(problem: str, lenses: list[str] | None = None) -> str:
    """Generate candidate ideas across SCAMPER lenses (all seven by default), one per
    lens. Optionally pass a subset of lens names."""
    chosen = [c for c in (_match(l) for l in (lenses or list(LENSES))) if c]
    if not chosen:
        chosen = list(LENSES)
    ideas = [apply_lens(problem, lens) for lens in chosen]
    return f"SCAMPER — {len(ideas)} candidate(s) for: {problem}\n\n" + "\n\n".join(ideas)
