/**
 * TRIZ tools backed by the pytriz engine over HTTP (EngineClient) — the
 * in-process replacement for the external MCP server.
 *
 * Tool NAMES intentionally match the pytriz MCP tools so the solver-agent's
 * subagent tool-filters (parameter-mapper, principle-finder,
 * solution-synthesizer) keep working unchanged.
 */
import { tool } from '@langchain/core/tools';
import type { DynamicStructuredTool } from '@langchain/core/tools';
import { z } from 'zod';
import { EngineClient } from '../domain/engine.client';
import { Param, Principle } from './contract';
import { RunContext } from './run-context';

function pick<T>(obj: any, keys: string[]): T | undefined {
  for (const k of keys) {
    if (obj != null && obj[k] != null) return obj[k] as T;
  }
  return undefined;
}

/** Canonical names of the 39 TRIZ engineering parameters — used as a guaranteed
 *  fallback so a param never renders as a bare "Parameter {id}". */
const TRIZ_PARAM_NAMES: Record<number, string> = {
  1: 'Weight of moving object',
  2: 'Weight of stationary object',
  3: 'Length of moving object',
  4: 'Length of stationary object',
  5: 'Area of moving object',
  6: 'Area of stationary object',
  7: 'Volume of moving object',
  8: 'Volume of stationary object',
  9: 'Speed',
  10: 'Force',
  11: 'Stress or pressure',
  12: 'Shape',
  13: 'Stability of the object',
  14: 'Strength',
  15: 'Duration of action of moving object',
  16: 'Duration of action of stationary object',
  17: 'Temperature',
  18: 'Illumination intensity',
  19: 'Use of energy by moving object',
  20: 'Use of energy by stationary object',
  21: 'Power',
  22: 'Loss of energy',
  23: 'Loss of substance',
  24: 'Loss of information',
  25: 'Loss of time',
  26: 'Quantity of substance',
  27: 'Reliability',
  28: 'Measurement accuracy',
  29: 'Manufacturing precision',
  30: 'External harm affecting the object',
  31: 'Harmful factors generated by the object',
  32: 'Ease of manufacture',
  33: 'Ease of operation',
  34: 'Ease of repair',
  35: 'Adaptability or versatility',
  36: 'Device complexity',
  37: 'Difficulty of detecting and measuring',
  38: 'Extent of automation',
  39: 'Productivity',
};

/** Best available name for a TRIZ parameter id: canonical table, else generic. */
function paramName(id: number, provided?: string | null): string {
  const trimmed = provided?.trim();
  if (trimmed) return trimmed;
  return TRIZ_PARAM_NAMES[id] ?? `Parameter ${id}`;
}

/** Canonical names of the 40 TRIZ inventive principles — used as a guaranteed
 *  fallback so a principle never renders as a bare "Principle {id}". */
const TRIZ_PRINCIPLE_NAMES: Record<number, string> = {
  1: 'Segmentation',
  2: 'Taking out',
  3: 'Local quality',
  4: 'Asymmetry',
  5: 'Merging',
  6: 'Universality',
  7: 'Nested doll',
  8: 'Anti-weight',
  9: 'Preliminary anti-action',
  10: 'Preliminary action',
  11: 'Beforehand cushioning',
  12: 'Equipotentiality',
  13: 'The other way round',
  14: 'Spheroidality – curvature',
  15: 'Dynamics',
  16: 'Partial or excessive actions',
  17: 'Another dimension',
  18: 'Mechanical vibration',
  19: 'Periodic action',
  20: 'Continuity of useful action',
  21: 'Skipping',
  22: 'Blessing in disguise',
  23: 'Feedback',
  24: 'Intermediary',
  25: 'Self-service',
  26: 'Copying',
  27: 'Cheap short-living objects',
  28: 'Mechanics substitution',
  29: 'Pneumatics and hydraulics',
  30: 'Flexible shells and thin films',
  31: 'Porous materials',
  32: 'Color changes',
  33: 'Homogeneity',
  34: 'Discarding and recovering',
  35: 'Parameter changes',
  36: 'Phase transitions',
  37: 'Thermal expansion',
  38: 'Strong oxidants',
  39: 'Inert atmosphere',
  40: 'Composite materials',
};

/** Best available name for a TRIZ principle id: provided, canonical table, else generic. */
export function principleName(id: number, provided?: string | null): string {
  const trimmed = provided?.trim();
  if (trimmed) return trimmed;
  return TRIZ_PRINCIPLE_NAMES[id] ?? `Principle ${id}`;
}

/** Unwrap common envelopes the engine may nest a param under. */
function unwrap(raw: any): any {
  return raw?.parameter ?? raw?.data ?? raw?.result ?? raw?.item ?? raw;
}

function normParam(raw: any): Param | null {
  const obj = unwrap(raw);
  if (obj == null) return null;
  const id = Number(pick<number>(obj, ['id', 'parameter_id', 'number', 'index']));
  if (!id) return null;
  const name = pick<string>(obj, ['name', 'title', 'label', 'parameter']);
  return { id, name: paramName(id, name) };
}

function normPrinciple(raw: any): Principle | null {
  if (raw == null) return null;
  const id = Number(pick<number>(raw, ['id', 'principle_id', 'number', 'index']));
  const name = pick<string>(raw, ['name', 'title', 'label', 'principle']);
  if (!id) return null;
  return {
    id,
    name: principleName(id, name),
    description: pick<string>(raw, ['description', 'desc', 'summary', 'text']),
  };
}

function normPrincipleList(raw: any): Principle[] {
  const arr: any[] = Array.isArray(raw)
    ? raw
    : raw?.principles ?? raw?.results ?? raw?.items ?? [];
  return arr.map(normPrinciple).filter((p): p is Principle => !!p);
}

function asString(value: unknown): string {
  try {
    return JSON.stringify(value);
  } catch {
    return String(value);
  }
}

/**
 * Engine calls must never abort the agent run: if the pytriz engine is down or
 * a lookup fails, return a note so the LLM can fall back on its own TRIZ
 * knowledge and keep driving the UI flow.
 */
interface SafeResult<T> {
  ok: boolean;
  value: T | null;
  note: string;
}

async function safeCall<T>(fn: () => Promise<T>): Promise<SafeResult<T>> {
  try {
    return { ok: true, value: await fn(), note: '' };
  } catch (err) {
    return {
      ok: false,
      value: null,
      note: `TRIZ engine unavailable (${(err as Error).message}). Use your own TRIZ knowledge to continue.`,
    };
  }
}

export function buildEngineTrizTools(
  engine: EngineClient,
  ctx: RunContext,
): DynamicStructuredTool[] {
  const searchParameter = tool(
    async ({ query }) => {
      const res = await safeCall(() => engine.searchParameters(query, 6));
      return res.ok ? asString(res.value) : res.note;
    },
    {
      name: 'search_parameter',
      description:
        'Search TRIZ engineering parameters (1–39) by free-text query. Returns candidate parameters with ids and names.',
      schema: z.object({ query: z.string().describe('free-text parameter query') }),
    },
  );

  const getParameterById = tool(
    async ({ id }) => {
      const res = await safeCall(() => engine.getParameter(id));
      return res.ok ? asString(res.value) : res.note;
    },
    {
      name: 'get_parameter_by_id',
      description: 'Fetch a single TRIZ parameter (1–39) by its numeric id.',
      schema: z.object({ id: z.number().int().describe('parameter id 1–39') }),
    },
  );

  const browseContradictionMatrix = tool(
    async ({ improving_id, worsening_id }) => {
      const cellRes = await safeCall(() => engine.matrixCell(improving_id, worsening_id));
      const principles = cellRes.ok ? normPrincipleList(cellRes.value) : [];

      // Enrich param names so the FE can render the contradiction.
      const [impRes, preRes] = await Promise.all([
        safeCall(() => engine.getParameter(improving_id)),
        safeCall(() => engine.getParameter(worsening_id)),
      ]);
      const improving = (impRes.ok && normParam(impRes.value)) || { id: improving_id, name: paramName(improving_id) };
      const preserving = (preRes.ok && normParam(preRes.value)) || { id: worsening_id, name: paramName(worsening_id) };
      ctx.setContradiction(improving, preserving);
      // Only record principles when the matrix actually returned some. Pinning an
      // empty matrix would (a) show an empty generation/shortlist screen and
      // (b) suppress the LLM-knowledge backfill in the runner, leaving the flow
      // stuck on "Brak zasad" whenever the engine is unavailable.
      if (principles.length) {
        ctx.setPrinciples(improving_id, worsening_id, principles);
      }

      return cellRes.ok ? asString(cellRes.value) : cellRes.note;
    },
    {
      name: 'browse_contradiction_matrix',
      description:
        'Look up the TRIZ contradiction matrix cell for an improving vs. worsening parameter pair. Returns the recommended inventive principles.',
      schema: z.object({
        improving_id: z.number().int().describe('improving parameter id (1–39)'),
        worsening_id: z.number().int().describe('worsening parameter id (1–39)'),
      }),
    },
  );

  const getPrincipleById = tool(
    async ({ id }) => {
      const res = await safeCall(() => engine.getPrinciple(id));
      return res.ok ? asString(res.value) : res.note;
    },
    {
      name: 'get_principle_by_id',
      description: 'Fetch a single TRIZ inventive principle (1–40) by its numeric id.',
      schema: z.object({ id: z.number().int().describe('principle id 1–40') }),
    },
  );

  const searchPrinciple = tool(
    async ({ query }) => {
      const res = await safeCall(() => engine.listPrinciples());
      if (!res.ok) return res.note;
      const all = normPrincipleList(res.value);
      const q = query.toLowerCase();
      const hits = all.filter(
        (p) => p.name.toLowerCase().includes(q) || (p.description ?? '').toLowerCase().includes(q),
      );
      return asString((hits.length ? hits : all).slice(0, 8));
    },
    {
      name: 'search_principle',
      description: 'Search TRIZ inventive principles (1–40) by free-text query.',
      schema: z.object({ query: z.string().describe('free-text principle query') }),
    },
  );

  return [
    searchParameter,
    getParameterById,
    browseContradictionMatrix,
    getPrincipleById,
    searchPrinciple,
  ];
}
